# Generated by Django 4.1.7 on 2023-03-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('users', '0004_alter_user_firstname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
