# Generated by Django 4.1.7 on 2023-02-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercises', models.ManyToManyField(related_name='workouts', to='exercises.exercise')),
                ('muscles_worked', models.ManyToManyField(related_name='workouts', to='exercises.muscle')),
            ],
        ),
    ]
