# Generated by Django 4.1.7 on 2023-03-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('exercises', '0001_initial'),
        ('workouts', '0002_remove_workout_exercises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('days_per_week', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
                ('workout_days', models.ManyToManyField(to='workouts.workoutday')),
            ],
        ),
        migrations.RemoveField(
            model_name='exerciseinstance',
            name='workout',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.AddField(
            model_name='workoutday',
            name='exercises',
            field=models.ManyToManyField(through='workouts.ExerciseInstance', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='muscles_worked',
            field=models.ManyToManyField(related_name='workout_days', to='exercises.muscle'),
        ),
        migrations.AddField(
            model_name='exerciseinstance',
            name='workout_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutday'),
            preserve_default=False,
        ),
    ]
